### ISSUE TITLE
Upstream changes?

### ISSUE THREAD

**Issue by andyrichardson** [ramonsnir/passport-workos#1]
Hey there, I came across this repo I'm wondering if there's anything I can do to help remove need for multiple packages?

> The behavior of the two strategies differs when used not as a callback (this library fails with 401, the other library redirects to WorkOS for authentication)

From the description, it sounds like you want to skip the initial authorization step [example here](https://www.passportjs.org/concepts/delegated-authorization/) and only handle the callback. Would this solve your problem?

```js
app.get(
  '/auth/workos/callback',
  (req, res, next) => {
    if (!req.query.code) {
      return res.status(401).send("Missing query parameter 'code'")
    }

    next();
  },
  passport.authenticate('oauth2'));
```

Hope this helps :crossed_fingers: let me know if you have anything in mind that you want to get upstream and I'll see what I can do :+1:

**Comment by ramonsnir** [comment]
Hi @andyrichardson,

I no longer have access to the source code of the application that uses this library, so I can't say if this would help or not. That application has several abstractions around authentication and it might have been a requirement for this strategy to behave exactly the same as the others used by the application. The README also says that there are type differences, but I can't say which were essential and which weren't.

I don't believe anyone else is using this package. If you'd like me to change anything in the README to emphasize that your package is better supported (although I don't believe anyone is confused), feel free to make a suggestion and I'll accept it.

**Comment by andyrichardson** [comment]
Hey @ramonsnir, no need for changes - just looking to help out! All the best!
